# 워크플로우의 이름 지정
name: CI

# 워크플로우가 시작될 조건 지정
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정
    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3 # GitHub 저장소의 소스 코드를 CI 서버로 체크아웃 (clone) 합니다.

      - uses: actions/setup-java@v3 # 자바 개발 환경을 설정합니다. Zulu 배포판의 Java 17을 설치합니다.
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew # gradlew 실행 권한 부여
        run: chmod +x gradlew # gradlew 스크립트 파일에 실행 권한을 부여합니다 (리눅스에서 필요).

      - name: Build with Gradle # Gradle을 사용해 프로젝트를 클린 후 빌드합니다.
        run: ./gradlew clean build # clean: 기존 빌드 결과물 제거 / build: 새로 빌드 실행 (컴파일 + 테스트 포함)